name: Build and Release TTF & WOFF2 (Nix)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build fonts with Nix
        run: nix build

      - name: Find generated TTF files
        id: ttf_files
        run: echo "files=$(find ./result -name '*.ttf' -printf '%p,' 2>/dev/null | sed 's/,$//' || echo '')" >> $GITHUB_OUTPUT

      - name: Find generated WOFF2 files
        id: woff2_files
        run: echo "files=$(find ./result -name '*.woff2' -printf '%p,' 2>/dev/null | sed 's/,$//' || echo '')" >> $GITHUB_OUTPUT

      - name: Upload TTF files to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.ttf_files.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload WOFF2 files to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.woff2_files.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
